# practice project

In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv("C:/Users/DHEERAJ/Desktop/100DaysML/practice_projects/practice1/modified_placement_data.csv")

In [ ]:
# just an overview of dataset( five five rows).
df.head()

  cgpa     iq placement
0  6,8  123.0       Yes
1  5,9  106.0        No
2  5,3  121.0        No
3  7,4  132.0       Yes
4  5,8  142.0        No

In [ ]:
# just an overview of dataset ( last five rows).
df.tail()

   cgpa     iq placement
95  4,3  200.0        No
96  4,4   42.0        No
97  6,7  182.0       Yes
98  6,3  103.0       Yes
99  6,2  113.0       Yes

steps:-
0. preprocessing +EDA + Feature selection .
1. extract input and output cols
2. Scale the values
3. train test split
4. train the model
5. evaluate the model/model selection
6. deploy the model